<a href="https://colab.research.google.com/github/VaibhavAvdhut/Data_Science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
import pandas as pd

In [ ]:
seq_list =[100,200,300,400,500]

In [ ]:
seq_list

[100, 200, 300, 400, 500]

In [ ]:
type(seq_list)

list

In [ ]:
seq_arr = np.array(seq_list)

In [ ]:
type(seq_arr)

numpy.ndarray

In [ ]:
seq_arr

array([100, 200, 300, 400, 500])

In [ ]:
seq_list

[100, 200, 300, 400, 500]

In [ ]:
seq_list2 = [[101,102,103],[104,105,106],[107,108,109]]

In [ ]:
type(seq_list2)

list

In [ ]:
np.array(seq_list2)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [ ]:
seq_arr2 = (np.array(seq_list2))

In [ ]:
seq_arr2

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [ ]:
type(seq_arr2)

numpy.ndarray

In [ ]:
seq_list

[100, 200, 300, 400, 500]

In [ ]:
seq_arr

array([100, 200, 300, 400, 500])

In [ ]:
seq_list2

[[101, 102, 103], [104, 105, 106], [107, 108, 109]]

In [ ]:
seq_arr2

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [ ]:
range(0,10)

range(0, 10)

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(range(8,20))

[8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [ ]:
list(range(8,20,3))

[8, 11, 14, 17]

In [ ]:
np.arange(-10,20,5)

array([-10,  -5,   0,   5,  10,  15])

In [ ]:
np.arange(8,20,3)

array([ 8, 11, 14, 17])

In [ ]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
zero_arr = np.zeros((10,5))

In [ ]:
zero_arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
type(zero_arr)

numpy.ndarray

In [ ]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
arr_ones = np.ones((7,7))

In [ ]:
type(arr_ones)

numpy.ndarray

In [ ]:
arr_ones

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.ones((7,7))*9

array([[9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9.]])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
np.zeros(10,dtype=int)+5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
np.linspace(0,5,3,dtype=int)

array([0, 2, 5])

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(10,30,5)

array([10., 15., 20., 25., 30.])

In [ ]:
np.linspace(10,30,50)

array([10.        , 10.40816327, 10.81632653, 11.2244898 , 11.63265306,
       12.04081633, 12.44897959, 12.85714286, 13.26530612, 13.67346939,
       14.08163265, 14.48979592, 14.89795918, 15.30612245, 15.71428571,
       16.12244898, 16.53061224, 16.93877551, 17.34693878, 17.75510204,
       18.16326531, 18.57142857, 18.97959184, 19.3877551 , 19.79591837,
       20.20408163, 20.6122449 , 21.02040816, 21.42857143, 21.83673469,
       22.24489796, 22.65306122, 23.06122449, 23.46938776, 23.87755102,
       24.28571429, 24.69387755, 25.10204082, 25.51020408, 25.91836735,
       26.32653061, 26.73469388, 27.14285714, 27.55102041, 27.95918367,
       28.36734694, 28.7755102 , 29.18367347, 29.59183673, 30.        ])

In [ ]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
import random

In [ ]:
random.random()

0.8290264577501081

In [ ]:
random.sample([10,20,30,60,70,55,66,77],5)

[10, 55, 66, 70, 60]

In [ ]:
random.sample([10,20,30,60,70,55,66,77],5)

[66, 20, 55, 60, 70]

In [ ]:
np.random.rand(9)

array([0.28786474, 0.24956557, 0.77756388, 0.46003258, 0.91347817,
       0.62845315, 0.57976278, 0.12140427, 0.97860023])

In [ ]:
np.random.rand(10)

array([0.70695263, 0.64765259, 0.52673001, 0.80125186, 0.72479388,
       0.21679189, 0.89284489, 0.32459097, 0.17534193, 0.89162596])

In [ ]:
np.random.randn()

-0.6691919467256858

In [ ]:
np.random.randn(15)

array([-0.1801109 , -1.53688852,  0.75529081,  0.41385872,  0.82164984,
       -0.12180718,  1.36119575, -0.83930609,  0.25432976, -0.30394627,
       -0.22649579, -0.00707495, -0.30301442, -0.7048697 ,  0.87137702])

In [ ]:
np.random.randint(8)

6

In [ ]:
np.random.randint(10,50,5)

array([14, 44, 26, 18, 18])

In [ ]:
arr1 =np.arange(50)

In [ ]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr1.shape

(50,)

In [ ]:
arr1.shape[0]

50

In [ ]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
arr1.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
arr2d =arr1.reshape(5,10)

In [ ]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr2d=arr1.reshape(50,1)

In [ ]:
arr2d


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49]])

In [ ]:
arr = np.arange(0,30,5)

In [ ]:
arr

array([ 0,  5, 10, 15, 20, 25])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr

array([ 0,  5, 10, 15, 20, 25])

In [ ]:
arr.max()

25

In [ ]:
arr.min()

0

In [ ]:
arr.mean()

12.5

In [ ]:
arr.sum()

75

In [ ]:
arr.argmax()

5

In [ ]:
arr.argmin()

0

In [ ]:
arr

array([ 0,  5, 10, 15, 20, 25])

In [ ]:
arr.cumsum()

array([ 0,  5, 15, 30, 50, 75])

In [ ]:
help(arr.cumsum())

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [ ]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    .. note::
        New code should use the ``standard_normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distribution is returned if no argument is provided.
 

In [ ]:
arr.sort()

In [ ]:
arr

array([ 0,  5, 10, 15, 20, 25])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr

array([ 0,  5, 10, 15, 20, 25])

In [ ]:
arr[3]

15

In [ ]:
arr[1]

5

In [ ]:
arr[5]

25

In [ ]:
arr[-1]

25

In [ ]:
arr[2:5]

array([10, 15, 20])

In [ ]:
arr[0:2]

array([0, 5])

In [ ]:
arr[::-1]

array([25, 20, 15, 10,  5,  0])

In [ ]:
arr[10:]

array([], dtype=int64)

In [ ]:
arr[0:10]

array([ 0,  5, 10, 15, 20, 25])

In [ ]:
arr[2:110]

array([10, 15, 20, 25])

In [ ]:
arr

array([ 0,  5, 10, 15, 20, 25])

In [ ]:
arr[2:5]

array([10, 15, 20])

In [ ]:
arr3 = arr[2:5]

In [ ]:
arr3[1:]

array([15, 20])

In [ ]:
arr[1:]

array([ 5, 10, 15, 20, 25])

In [ ]:
arr3

array([10, 15, 20])

In [ ]:
arr

array([ 0,  5, 10, 15, 20, 25])

In [ ]:
arr_copy=arr.copy()


In [ ]:
arr_copy

array([ 0,  5, 10, 15, 20, 25])

In [ ]:
from copy import copy,deepcopy

In [ ]:
data1 = [20,40,[60,70]]

In [ ]:
data1

[20, 40, [60, 70]]

In [ ]:
deep_copy_data1=deepcopy(data1)

In [ ]:
deep_copy_data1

[20, 40, [60, 70]]

In [ ]:
shallow_copy_data1=copy(data1)

In [ ]:
shallow_copy_data1

[20, 40, [60, 70]]

In [ ]:
data1

[20, 40, [60, 70]]

In [ ]:
deep_copy_data1

[20, 40, [60, 70]]

In [ ]:
shallow_copy_data1

[20, 40, [60, 70]]

In [ ]:
deep_copy_data1=78

In [ ]:
data1

[20, 40, [60, 70]]

In [ ]:
shallow_copy_data1

[20, 40, [60, 70]]

In [ ]:
shallow_copy_data1=78

In [ ]:
data1

[20, 40, [60, 70]]

In [ ]:
arr2d =[[11,12,13],[56,78,99],[33,34,89]]

In [ ]:
arr2d

[[11, 12, 13], [56, 78, 99], [33, 34, 89]]

In [ ]:
arr2d=np.array(arr2d)

In [ ]:
arr2d

array([[11, 12, 13],
       [56, 78, 99],
       [33, 34, 89]])

In [ ]:
arr2d[2]

array([33, 34, 89])

In [ ]:
arr2d[1,2]

99

In [ ]:
arr2d[1,1]

78

In [ ]:
arr2d[2,2]

89

In [ ]:
arr2d

array([[11, 12, 13],
       [56, 78, 99],
       [33, 34, 89]])

In [ ]:
arr2d[1,1:]

array([78, 99])

In [ ]:
arr2d[2,0:2]

array([33, 34])

In [ ]:
arr2d[:,0]

array([11, 56, 33])

In [ ]:
arr2d[:,0:1]

array([[11],
       [56],
       [33]])

In [ ]:
arr2d[:,1]

array([12, 78, 34])

In [ ]:
arr2d[:,1:2]

array([[12],
       [78],
       [34]])

In [ ]:
arr2d[1:,1:2]

array([[78],
       [34]])

In [ ]:
arr2d

array([[11, 12, 13],
       [56, 78, 99],
       [33, 34, 89]])

In [ ]:
arr2d[[0,1],[0,2]]

array([11, 99])

In [ ]:
np.eye(9)*9

array([[9., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 9., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 9., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 9., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 9., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 9., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 9.]])

In [ ]:
np.ones(9)*9

array([9., 9., 9., 9., 9., 9., 9., 9., 9.])

In [ ]:
np.ones((9,9))*9

array([[9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9.]])